dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - "1.13.x"
before_install:
  - go get github.com/mattn/goveralls

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- TF_ACC=1 go test -v -covermode=count -coverprofile=coverage.out ./tumblr/
- $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
